on:
  push:
    branches: [develop]

permissions:
  id-token: write  # Ensure this permission is set

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular app
        run: ng build

      - name: List build directory contents
        run: ls -la dist/concept

  UploadArtifact:
    needs: build
    runs-on: ubuntu-lates

    steps:
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: dist/concept

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Remove existing files
        run: |
          git config --global user.email "andreadistefano98@gmail.com"
          git config --global user.name "galvanizedheart"
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          git add .
          git commit -m "Clean main branch"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          folder: dist/concept
          branch: main
