name: Build and Deploy Angular App

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build

      - name: Deploy to main branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          git add ./dist/concept/browser/*
          git commit -m 'Deploy to main branch'
          git push origin main
